version: 2
enable-beta-ecosystems: true
updates:
  # Workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Workspace pubspec.yaml
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Examples
  - package-ecosystem: 'pub'
    directory: '/examples/dartnote'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/explorer'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/manifest'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/service_manager_cli'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/snake'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/task_dialog'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/task_manager'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/tetris'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/examples/usb_drive_monitor'
    schedule:
      interval: 'weekly'

  # Packages
  - package-ecosystem: 'pub'
    directory: '/packages/ffi_leak_tracker'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/packages/generator'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/packages/win32'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/packages/win32_clipboard'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/packages/win32_registry'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'pub'
    directory: '/packages/win32_runner'
    schedule:
      interval: 'weekly'
