name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.4.4
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^1.1.0

dev_dependencies:
  # Handle command-line arguments for development tooling.
  args: ^2.3.0
  
  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.2.1

  # Help ensure that the code is well-written.
  lints: ^1.0.1

  # Used for joining paths, as part of our path_provider integration test.
  path: ^1.8.1

  # Running the test suite.
  test: ^1.20.2

  # Windows metadata for automatically generating API signatures. The
  # relationship between these two packages is tightly coupled, since this
  # package includes a specific version of the Win32 metadata, so we pin the
  # dependency by version to avoid surprising conflicts.
  winmd: 1.0.27
