name: win32_clipboard
description: A package that provides a friendly Dart API for accessing the
  Windows Clipboard.
version: 0.1.1
homepage: https://win32.pub
repository: https://github.com/dart-windows/win32_clipboard
issue_tracker: https://github.com/dart-windows/win32_clipboard/issues

topics:
  - clipboard
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.1.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.0
  win32: ^5.0.9

dev_dependencies:
  checks: ^0.2.2
  dartwindows_lints: ^1.0.0
  melos: ">=3.1.1 <5.0.0"
  test: ^1.24.6
