name: win32_gamepad
description: A package that provides a friendly Dart API for accessing gamepads
  connected to a Windows machine.
version: 1.0.9
repository: https://github.com/halildurmus/win32_gamepad
issue_tracker: https://github.com/halildurmus/win32_gamepad/issues

topics:
  - gamepad
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.4.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.2
  win32: ^5.5.1

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.25.8
