name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.0.0-nullsafety.10
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://win32.pub

environment:
  sdk: '>=2.12.0-259.8 <3.0.0'

dependencies:
  ffi: '>=0.3.0-nullsafety.1 <2.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.15
  winmd:
    path: ../winmd