name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 1.7.4
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://win32.pub

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  lint: ^1.3.0
  test: ^1.14.2