name: win32_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - examples/dartnote
  - examples/manifest
  - examples/service_manager_cli
  - examples/snake
  - examples/system_tray_icon
  - examples/task_dialog
  - examples/tetris
  - examples/usb_drive_monitor
  - packages/win32_gamepad/example/inspector
  - packages/*

dev_dependencies:
  args: ^2.7.0
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  path: ^1.9.1
  win32: ^6.0.0
