name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 1.2.6
homepage: https://github.com/timsneath/win32

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2