name: win32
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 2.2.10
homepage: https://win32.pub
repository: https://github.com/timsneath/win32
issue_tracker: https://github.com/timsneath/win32/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  args: ^2.3.0
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.18.3
  winmd: 1.0.12 # Pinned deliberately
