name: win32_runner
description: A Dart runner for Flutter Windows apps â€” no C++ compiler required.
version: 0.2.4
repository: https://github.com/halildurmus/win32_runner
issue_tracker: https://github.com/halildurmus/win32_runner/issues

topics:
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.11.0

platforms:
  windows:

dependencies:
  args: ^2.7.0
  ffi: ^2.2.0
  path: ^1.9.1
  win32: ^6.0.0
  win32_registry: ^3.0.0

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
