name: winmd
description: A Dart package for working with Windows Metadata (.winmd) files.
version: 6.1.0
repository: https://github.com/halildurmus/winmd
issue_tracker: https://github.com/halildurmus/winmd/issues

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: ^3.7.0

platforms:
  windows:

dependencies:
  archive: ^4.0.2
  ffi: ^2.1.3
  logging: ^1.3.0
  nuget: ^0.2.0
  path: ^1.9.1

dev_dependencies:
  checks: ^0.3.0
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints
  test: ^1.25.15
