name: win32_runner
description: Compile and run a Flutter app without needing any C/C++ code. Just Dart!
version: 0.0.6
repository: https://github.com/timsneath/win32_runner

environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'

platforms:
  windows:

dependencies:
  args: ^2.3.0
  ffi: ^1.2.0-dev.0
  win32: ^2.3.10

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
