name: win32_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - examples/*
  - packages/*
  - packages/filepicker_windows/example/wallpaper
  - packages/win32_gamepad/example/inspector

dev_dependencies:
  args: ^2.7.0
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  image: ^4.8.0
  path: ^1.9.1
  win32: ^6.0.0
