name: task_manager
description: Task Manager
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.2.0
  ffi_leak_tracker:
    path: ../../packages/ffi_leak_tracker # TODO: update to ^0.1.0 when released
  flutter:
    sdk: flutter
  win32:
    path: ../../packages/win32 # TODO: update to ^6.0.0 when released

dev_dependencies:
  halildurmus_lints: ^2.0.0

flutter:
  uses-material-design: true
