name: task_manager
description: Task Manager
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  flutter:
    sdk: flutter
  win32: ^6.0.0

dev_dependencies:
  halildurmus_lints: ^2.0.0

flutter:
  uses-material-design: true
