name: win32
description: Call common Windows APIs directly from Dart using FFI.
version: 6.0.0
homepage: https://win32.pub
repository: https://github.com/halildurmus/win32
issue_tracker: https://github.com/halildurmus/win32/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22package%3A%20win32%22
documentation: https://win32.pub/docs
funding:
  - https://github.com/sponsors/halildurmus

screenshots:
  - description: Task Manager App screenshot
    path: screenshots/task_manager.png
  - description: DartNote App screenshot
    path: screenshots/dartnote.png
  - description: Tetris Game screenshot
    path: screenshots/tetris.png
  - description: Snake Game screenshot
    path: screenshots/snake.png

topics:
  - win32
  - windows
  - ffi

environment:
  sdk: ^3.11.0

resolution: workspace

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  hooks: ^1.0.0
  logging: ^1.3.0
  meta: ^1.17.0
  native_toolchain_c: ^0.17.4

dev_dependencies:
  # Handle command-line arguments for example apps.
  args: ^2.7.0

  # Used for expressing test expectations.
  checks: ^0.3.1

  # Used for running Git hooks.
  halildurmus_hooks: ^0.1.1

  # Help ensure that the code is well-written.
  halildurmus_lints: ^2.0.0

  # Used for joining paths.
  path: ^1.9.1

  # Running the test suite.
  test: ^1.29.0
