name: service_manager_cli
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  args: ^2.7.0
  ffi: ^2.2.0
  win32: ^6.0.0

dev_dependencies:
  halildurmus_lints: ^2.0.0

executables:
  service_manager_cli:
