name: service_manager_cli
description: Service Manager CLI
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  ffi: ^2.1.2
  win32: ^5.5.1

dev_dependencies:
  lints: ^4.0.0

executables:
  service_manager_cli:
