name: winmd
description: >
  Inspect and generate Windows Metadata (.winmd) files based on the ECMA-335
  standard.
version: 7.0.1
repository: https://github.com/halildurmus/winmd
issue_tracker: https://github.com/halildurmus/winmd/issues
funding:
  - https://github.com/sponsors/halildurmus

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: ^3.11.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  archive: ^4.0.9
  ffi: ^2.2.0
  logging: ^1.3.0
  meta: ^1.18.1
  nuget: ^0.2.1
  path: ^1.9.1

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
