name: win32_gamepad
description: >
  A modern, type-safe Dart API for accessing gamepads connected to a Windows
  machine.
version: 1.0.11
repository: https://github.com/halildurmus/win32/tree/main/packages/win32_gamepad
issue_tracker: https://github.com/halildurmus/win32/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22package%3A%20win32_gamepad%22
funding:
  - https://github.com/sponsors/halildurmus

topics:
  - gamepad
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.11.0

platforms:
  windows:

resolution: workspace

dependencies:
  ffi: ^2.2.0
  win32: ^6.0.0

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
