name: filepicker_windows
description: >
  File and directory picker for Windows that uses common dialog controls.
version: 3.0.1
repository: https://github.com/halildurmus/win32/tree/main/packages/filepicker_windows
issue_tracker: https://github.com/halildurmus/win32/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22package%3A%20filepicker_windows%22
funding:
  - https://github.com/sponsors/halildurmus

topics:
  - picker
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.11.0

platforms:
  windows:

resolution: workspace

dependencies:
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  win32: ^6.0.0

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
