name: filepicker_windows
description: >
  File and directory picker for Windows that uses common dialog controls.
version: 3.0.0
repository: https://github.com/halildurmus/filepicker_windows
issue_tracker: https://github.com/halildurmus/filepicker_windows/issues

topics:
  - picker
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.11.0

platforms:
  windows:

dependencies:
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  win32: ^6.0.0

dev_dependencies:
  checks: ^0.3.1
  halildurmus_hooks: ^0.1.1
  halildurmus_lints: ^2.0.0
  test: ^1.29.0
