name: win32_explorer
description: Drive explorer, built with Flutter
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  path_provider: ^2.1.5
  win32:
    path: ../../packages/win32

dev_dependencies:
  halildurmus_lints: ^2.0.0

flutter:
  uses-material-design: true
