name: win32_explorer
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.2.0
  ffi_leak_tracker: ^0.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  path_provider: ^2.1.5
  win32: ^6.0.0

dev_dependencies:
  halildurmus_lints: ^2.0.0

flutter:
  uses-material-design: true
