name: inspector
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  fluent_ui: ^4.14.0
  flutter:
    sdk: flutter
  win32_gamepad: ^1.0.11
  win32_registry: ^3.0.2

flutter:
  uses-material-design: true

dev_dependencies:
  halildurmus_lints: ^2.0.0
