name: Check Code Generation

on:
  pull_request:
    paths:
      - .github/workflows/code_generation.yml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml
      - tools/generate.cmd
  push:
    branches: [main]
    paths:
      - .github/workflows/code_generation.yml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml
      - tools/generate.cmd

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ“¦ Install Workspace Dependencies
        run: dart pub get

      - name: ğŸ“¦ Install package:win32 Dependencies
        run: dart pub get
        working-directory: packages/win32

      - name: ğŸ“¦ Install package:generator Dependencies
        run: dart pub get
        working-directory: packages/generator

      - name: ğŸš€ Run Code Generation
        run: tools\generate --no-test

      - name: ğŸ” Verify Code Generation
        run: git diff --exit-code
