name: Dart Examples

on:
  pull_request:
    paths:
      - .github/workflows/dart_examples.yml
      - analysis_options.yaml
      - pubspec.yaml
      - examples/com_interop/*
      - examples/*.dart
      - packages/win32/hook/**
      - packages/win32/lib/**
      - packages/win32/src/**
      - packages/win32/analysis_options.yaml
      - packages/win32/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/dart_examples.yml
      - analysis_options.yaml
      - pubspec.yaml
      - examples/com_interop/*
      - examples/*.dart
      - packages/win32/hook/**
      - packages/win32/lib/**
      - packages/win32/src/**
      - packages/win32/analysis_options.yaml
      - packages/win32/pubspec.yaml

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      # Exclude package examples like 'explorer' when analyzing and formatting
      # the Dart files. They are analyzed and formatted in another workflow.
      analyze_directories: $(find . -type f -not \( -path .*explorer/* -prune \) -not \( -path .*dartnote/* -prune \) -not \( -path .*manifest/* -prune \) -not \( -path .*service_manager_cli/* -prune \) -not \( -path .*snake/* -prune \) -not \( -path .*system_tray_icon/* -prune \) -not \( -path .*task_dialog/* -prune \) -not \( -path .*task_manager/* -prune \) -not \( -path .*tetris/* -prune \) -not \( -path .*usb_drive_monitor/* -prune \) -name '*.dart' -print)
      format_directories: $(find . -type f -not \( -path .*explorer/* -prune \) -not \( -path .*dartnote/* -prune \) -not \( -path .*manifest/* -prune \) -not \( -path .*service_manager_cli/* -prune \) -not \( -path .*snake/* -prune \) -not \( -path .*system_tray_icon/* -prune \) -not \( -path .*task_dialog/* -prune \) -not \( -path .*task_manager/* -prune \) -not \( -path .*tetris/* -prune \) -not \( -path .*usb_drive_monitor/* -prune \) -name '*.dart' -print)
      run_tests: false
      working_directory: examples
