name: generator

on:
  pull_request:
    paths:
      - .github/workflows/generator.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/data/**
      - packages/generator/example/**
      - packages/generator/lib/**
      - packages/generator/test/**
      - packages/generator/analysis_options.yaml
      - packages/generator/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/generator.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/data/**
      - packages/generator/example/**
      - packages/generator/lib/**
      - packages/generator/test/**
      - packages/generator/analysis_options.yaml
      - packages/generator/pubspec.yaml

jobs:
  build:
    strategy:
      matrix:
        os: [windows]
        sdk: [main, stable]

    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      analyze_directories: bin example lib test
      check_coverage: ${{ matrix.sdk == 'main' }}
      codecov_flags: generator
      concurrency: '1'
      flutter_channel: ${{ matrix.sdk }}
      format_directories: bin example lib test
      runs_on: ${{ matrix.os }}-latest
      working_directory: packages/generator
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
