name: generator

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/generator.yml'
      - 'analysis_options.yaml'
      - 'codecov.yml'
      - 'pubspec.yaml'
      - 'packages/generator/bin/**'
      - 'packages/generator/example/**'
      - 'packages/generator/lib/**'
      - 'packages/generator/test/**'
      - 'packages/generator/analysis_options.yaml'
      - 'packages/generator/pubspec.yaml'
  push:
    branches: [main]
    paths:
      - '.github/workflows/generator.yml'
      - 'analysis_options.yaml'
      - 'codecov.yml'
      - 'pubspec.yaml'
      - 'packages/generator/bin/**'
      - 'packages/generator/example/**'
      - 'packages/generator/lib/**'
      - 'packages/generator/test/**'
      - 'packages/generator/analysis_options.yaml'
      - 'packages/generator/pubspec.yaml'
  schedule:
    # Run every day at 4:00 AM UTC.
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      # We want to see the results on stable even if main fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false

      # Free config supports up to 20 concurrent jobs, so pick a sparse matrix
      # that tiles the space well.
      matrix:
        include:
          - os: windows-latest
            sdk: main
          - os: windows-2022
            sdk: beta
          - os: windows-2019
            sdk: stable

    uses: halildurmus/workflows/.github/workflows/dart_package.yml@main
    with:
      dart_sdk: ${{ matrix.sdk }}
      run_tests: ${{ matrix.sdk != 'main' }}
      runs_on: ${{ matrix.os }}
      upload_coverage: ${{ matrix.sdk == 'main' }}
      working_directory: packages/generator
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
