name: win32_clipboard

on:
  pull_request:
    paths:
      - .github/workflows/win32_clipboard.yml
      - lib/**
      - test/**
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/win32_clipboard.yml
      - lib/**
      - test/**
      - pubspec.yaml

jobs:
  build:
    strategy:
      # We want to see the results on stable even if main fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false

      # Free config supports up to 20 concurrent jobs, so pick a sparse matrix
      # that tiles the space well.
      matrix:
        include:
          - os: windows-latest
            sdk: main
          - os: windows-2022
            sdk: beta
          - os: windows-2019
            sdk: stable
          - os: ubuntu-latest
            sdk: stable
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      check_coverage: ${{ matrix.sdk == 'main' }}
      concurrency: '1'
      dart_sdk: ${{ matrix.sdk }}
      format_directories: lib test
      runs_on: ${{ matrix.os }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dartdoc:
    needs: [build]
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main

  pana:
    needs: [build]
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
