name: win32

on:
  pull_request:
    paths:
      - .github/workflows/win32.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - examples/**
      - packages/win32/hook/**
      - packages/win32/lib/**
      - packages/win32/src/**
      - packages/win32/test/**
      - packages/win32/test_fixes/**
      - packages/win32/analysis_options.yaml
      - packages/win32/CHANGELOG.md
      - packages/win32/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/win32.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - examples/**
      - packages/win32/hook/**
      - packages/win32/lib/**
      - packages/win32/src/**
      - packages/win32/test/**
      - packages/win32/test_fixes/**
      - packages/win32/analysis_options.yaml
      - packages/win32/CHANGELOG.md
      - packages/win32/pubspec.yaml
  schedule:
    - cron: 0 12 * * * # Run every day at 12:00 UTC

jobs:
  build:
    strategy:
      # We want to see the results on stable even if dev fails (and vice versa).
      # This prevents one failure from stopping the entire run.
      fail-fast: false

      matrix:
        include:
          - os: windows-2025
            sdk: dev
          - os: windows-2022
            sdk: beta
          - os: windows-2022
            sdk: stable
          - os: ubuntu-latest
            sdk: stable

    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      check_coverage: ${{ matrix.sdk == 'dev' }}
      codecov_flags: win32
      concurrency: '1'
      dart_sdk: ${{ matrix.sdk }}
      format_directories: lib test
      randomize_execution_order_of_tests: true
      runs_on: ${{ matrix.os }}
      working_directory: packages/win32
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dartdoc:
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main
    with:
      working_directory: packages/win32

  dart_examples:
    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      # Only analyze/format standalone Dart files and the com_interop directory.
      analyze_directories: com_interop $(find . -maxdepth 1 -name '*.dart' -print)
      format_directories: com_interop $(find . -maxdepth 1 -name '*.dart' -print)
      run_tests: false
      working_directory: examples

  dart_package_examples:
    strategy:
      matrix:
        example:
          - dartnote
          - manifest
          - service_manager_cli
          - snake
          - system_tray_icon
          - task_dialog
          - tetris
          - usb_drive_monitor

    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      analyze_directories: bin lib
      format_directories: bin lib
      run_tests: false
      working_directory: examples/${{ matrix.example }}

  flutter_examples:
    strategy:
      matrix:
        example:
          - explorer
          - task_manager

    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      analyze_directories: lib
      format_directories: lib
      run_tests: false
      working_directory: examples/${{ matrix.example }}

  pana:
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
    with:
      working_directory: packages/win32
