name: win32_clipboard

on:
  pull_request:
    paths:
      - .github/workflows/win32_clipboard.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - packages/win32_clipboard/lib/**
      - packages/win32_clipboard/test/**
      - packages/win32_clipboard/example/**
      - packages/win32_clipboard/analysis_options.yaml
      - packages/win32_clipboard/CHANGELOG.md
      - packages/win32_clipboard/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/win32_clipboard.yml
      - analysis_options.yaml
      - codecov.yml
      - pubspec.yaml
      - packages/win32_clipboard/lib/**
      - packages/win32_clipboard/test/**
      - packages/win32_clipboard/example/**
      - packages/win32_clipboard/analysis_options.yaml
      - packages/win32_clipboard/CHANGELOG.md
      - packages/win32_clipboard/pubspec.yaml

jobs:
  build:
    strategy:
      # We want to see the results on stable even if dev fails (and vice versa).
      # This prevents one failure from stopping the entire run.
      fail-fast: false

      matrix:
        include:
          - os: windows-2025
            sdk: main
          - os: windows-2022
            sdk: beta
          - os: windows-2022
            sdk: stable
          - os: ubuntu-latest
            sdk: stable

    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      check_coverage: ${{ matrix.sdk == 'main' }}
      codecov_flags: win32_clipboard
      concurrency: '1'
      flutter_channel: ${{ matrix.sdk }}
      format_directories: lib test
      randomize_execution_order_of_tests: true
      runs_on: ${{ matrix.os }}
      working_directory: packages/win32_clipboard
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dartdoc:
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main
    with:
      working_directory: packages/win32_clipboard

  examples:
    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      analyze_directories: example
      format_directories: example
      run_tests: false
      working_directory: packages/win32_clipboard

  pana:
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
    with:
      working_directory: packages/win32_clipboard
