name: winmd

on:
  pull_request:
    paths:
      - .github/workflows/winmd.yml
      - lib/**
      - test/**
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/winmd.yml
      - lib/**
      - test/**
      - pubspec.yaml

jobs:
  build:
    strategy:
      # We want to see the results on stable even if main fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false

      matrix:
        include:
          - os: windows-2025
            sdk: dev
          - os: windows-2022
            sdk: beta
          - os: windows-2022
            sdk: stable
          - os: windows-11-arm
            sdk: stable
          - os: macos-latest
            sdk: stable
          - os: ubuntu-latest
            sdk: stable

    uses: halildurmus/workflows/.github/workflows/dart.yml@main
    with:
      check_coverage: ${{ matrix.sdk == 'dev' }}
      concurrency: '1'
      dart_sdk: ${{ matrix.sdk }}
      format_directories: lib test
      randomize_execution_order_of_tests: true
      runs_on: ${{ matrix.os }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dartdoc:
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main

  pana:
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
